### PR TITLE
Upgrade to apollo v3

### PR DESCRIPTION
**Pull request by haodt**
Hello @ihorkatkov , i have upgraded the apollo dependencies to version 3, some to latest. Hope this would be merged. 

Let me known if you have any concerns.

### CODE REVIEW

**Comment by haodt** [comment]
Btw CI nodejs version need to be atleast 10 :)

**Comment by ckruse** [comment]
Ping? Is this project dead?

**Comment by ihorkatkov** [comment]
> Ping? Is this project dead?

It's not. I'm ready to merge the PR once CI is green

**Comment by ihorkatkov** [comment]
> Ping? Is this project dead?

**Comment by ckruse** [comment]
Good to read! :-)

**Comment by haodt** [comment]
sorry but im not familiar with semaphore CI, im stuck at bump its node version to 10 so that `yarn install` could work. Can you help please ?

**Comment by ihorkatkov** [comment]
Okay, I will take a look 👍

**Review by ihorkatkov — APPROVED** [review]

**Comment by ihorkatkov** [comment]
Done. Great job @haodt

**Pull request merged**
