### PR TITLE
fix: apollo-client no longer exports printAST

### LINKED ISSUE #20: apollo-client 2.4.10 no longer exports printAST
`apollo-client` no longer exports printAST. From the ChangeLog:

> The `apollo-client` package no longer exports a `printAST` function from `graphql/language/printer`. If you need this functionality, import it directly: `import { print } from "graphql/language/printer"`

This causes `apollo-absinthe-upload-link` to fail:

~~~
./node_modules/apollo-absinthe-upload-link/src/index.js                                                                 │ [208] ./js/dialer.js 4.21 kB {0} [built]
Attempted import error: 'printAST' is not exported from 'apollo-client'.   
~~~

### PR DESCRIPTION
**Pull request by ckruse**
fixes #20

### CODE REVIEW

**Comment by ckruse** [comment]
Ping? :-)

**Comment by ihorkatkov** [comment]
Hey. Thanks for the PR :) I will review it on next Monday

**Comment by ckruse** [comment]
Cool - thanks!

Didn't want to nag you, just wanted to send a friendly reminder. Sorry when I was unpolite :)

**Comment by ihorkatkov** [comment]
Hey. Thanks for the PR :) I will review it on next Monday

**Review by ihorkatkov — APPROVED** [review]

**Pull request merged**
